### PR TITLE
Refactor introduction to D pages

### PR DESCRIPTION
**Pull request by edi33416**

### CODE REVIEW

**Comment by edi33416** [comment]
Published at https://edi33416.github.io/DSS-gh-pages/refs/pull/24/merge

**Comment by edi33416** [comment]
Published at https://edi33416.github.io/DSS-gh-pages/refs/pull/24/merge

**Comment by edi33416** [comment]
Published at https://edi33416.github.io/DSS-gh-pages/refs/pull/24/merge

**Comment by edi33416** [comment]
Published at https://edi33416.github.io/DSS-gh-pages/refs/pull/24/merge

**Review by RazvanN7 — APPROVED** [review]

**Pull request merged**
